"use client";

import { useCallback, useEffect, useState } from "react";

import { NotificationManager } from "@/components/NotificationManager";
import {
  MarketsSection,
  NRLDrawSection,
  PortfolioSection,
  StoriesSection,
  WatchTodaySection,
} from "@/components/Sections";
import { WeatherWidget } from "@/components/WeatherWidget";
import { fetchDigest } from "@/lib/fetchDigest";
import type { Digest } from "@/lib/types";

function formatDate(iso: string) {
  if (!iso) return "";
  const d = new Date(iso);
  return new Intl.DateTimeFormat("en-AU", {
    weekday: "long",
    day: "numeric",
    month: "long",
    timeZone: "Australia/Brisbane",
  }).format(d);
}

export default function Page() {
  const [digest, setDigest] = useState<Digest | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      setDigest(await fetchDigest());
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  return (
    <main className="max-w-xl mx-auto px-4 pt-6 pb-12">
      <NotificationManager />
      <header className="mb-4">
        <div className="text-xs uppercase tracking-widest text-muted">Daily Digest</div>
        {digest && (
          <div className="text-sm text-gray-400 mt-0.5">{formatDate(digest.generated_at_utc)}</div>
        )}
        {digest && (
          <h1 className="text-2xl font-semibold leading-snug mt-2 font-serif">
            {digest.headline}
          </h1>
        )}
      </header>

      {loading && (
        <div className="section-card p-6 text-center text-muted">Loading today’s digest…</div>
      )}

      {error && !loading && (
        <div className="section-card p-6 border-negative/40">
          <div className="text-negative font-semibold mb-1">Couldn’t load digest</div>
          <div className="text-sm text-gray-400 mb-3">{error}</div>
          <button
            onClick={load}
            className="text-sm font-medium bg-white/10 px-3 py-1.5 rounded-md hover:bg-white/15"
          >
            Try again
          </button>
        </div>
      )}

      {digest && !loading && !error && (
        <>
          {digest.weather && <WeatherWidget weather={digest.weather} />}
          <WatchTodaySection items={digest.watch_today} />
          <PortfolioSection
            movers={digest.portfolio.movers}
            totals={digest.portfolio_totals}
          />
          <MarketsSection summary={digest.markets.summary} indicators={digest.markets.indicators} />
          <StoriesSection
            icon="🇦🇺"
            title="Australian Politics"
            summary={digest.politics.summary}
            stories={digest.politics.stories}
          />
          <StoriesSection
            icon="🤖"
            title="AI World"
            summary={digest.ai.summary}
            stories={digest.ai.stories}
          />
          <StoriesSection
            icon="🏉"
            title="Sport"
            summary={digest.sport.summary}
            stories={digest.sport.stories}
          />
          {digest.nrl_draw && (
            <NRLDrawSection
              fixtures={digest.nrl_draw}
              roundLabel={digest.nrl_round}
              byes={digest.nrl_byes}
            />
          )}
          <footer className="text-center text-[11px] text-muted mt-8">
            Pull to refresh · Generated by Claude
          </footer>
        </>
      )}
    </main>
  );
}
